'use strict';

const OBJECT_TYPES_BY_ENGINE = Object.freeze({
  sqlite: ['table', 'view', 'index', 'trigger'],
  postgresql: [
    'table',
    'view',
    'materializedView',
    'procedure',
    'function',
    'index',
    'trigger',
    'sequence',
    'type',
  ],
  mysql: ['table', 'view', 'procedure', 'function', 'index', 'trigger', 'event'],
  sqlserver: [
    'table',
    'view',
    'procedure',
    'function',
    'index',
    'trigger',
    'sequence',
    'type',
    'synonym',
  ],
  oracle: [
    'table',
    'view',
    'materializedView',
    'procedure',
    'function',
    'package',
    'index',
    'trigger',
    'sequence',
    'type',
    'synonym',
  ],
});

const OBJECT_LABELS = Object.freeze({
  table: 'Table',
  view: 'View',
  materializedView: 'Materialized View',
  procedure: 'Procedure',
  function: 'Function',
  package: 'Package',
  index: 'Index',
  trigger: 'Trigger',
  sequence: 'Sequence',
  type: 'Type',
  synonym: 'Synonym',
  event: 'Event',
});

function objectTypesForEngine(engineId) {
  return [...(OBJECT_TYPES_BY_ENGINE[engineId] || [])];
}

function createTemplate(
  engineId,
  objectType,
  qualifiedName,
  quoteIdentifier,
  options = {},
) {
  const q = quoteIdentifier;
  const tablePlaceholder = q('table');
  const columnPlaceholder = q('column');

  if (objectType === 'table') {
    const identity = {
      postgresql: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
      mysql: 'BIGINT AUTO_INCREMENT PRIMARY KEY',
      sqlserver: 'BIGINT IDENTITY(1,1) PRIMARY KEY',
      oracle: 'NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
      sqlite: 'INTEGER PRIMARY KEY',
    }[engineId] || 'INTEGER PRIMARY KEY';
    const textType = engineId === 'oracle' ? 'VARCHAR2(255)' : 'VARCHAR(255)';
    return `CREATE TABLE ${qualifiedName} (\n  ${q('id')} ${identity},\n  ${q('name')} ${textType} NOT NULL\n);`;
  }

  if (objectType === 'view') {
    const create = ['postgresql', 'oracle'].includes(engineId)
      ? 'CREATE OR REPLACE VIEW'
      : engineId === 'sqlserver'
        ? 'CREATE OR ALTER VIEW'
        : 'CREATE VIEW';
    return `${create} ${qualifiedName} AS\nSELECT *\nFROM ${tablePlaceholder};`;
  }

  if (objectType === 'materializedView') {
    return `CREATE MATERIALIZED VIEW ${qualifiedName} AS\nSELECT *\nFROM ${tablePlaceholder};`;
  }

  if (objectType === 'index') {
    // PostgreSQL, MySQL, and SQL Server derive the index schema from the table
    // and do not accept a schema-qualified index name in CREATE INDEX.
    const indexName = ['postgresql', 'mysql', 'sqlserver'].includes(engineId)
      ? options.identifierName || qualifiedName
      : qualifiedName;
    return `CREATE INDEX ${indexName}\nON ${tablePlaceholder} (${columnPlaceholder});`;
  }

  if (objectType === 'sequence') {
    if (engineId === 'sqlserver') {
      return `CREATE SEQUENCE ${qualifiedName}\n  AS BIGINT\n  START WITH 1\n  INCREMENT BY 1;`;
    }
    return `CREATE SEQUENCE ${qualifiedName}\n  START WITH 1\n  INCREMENT BY 1;`;
  }

  if (objectType === 'procedure' || objectType === 'function') {
    const isFunction = objectType === 'function';
    if (engineId === 'postgresql') {
      return isFunction
        ? `CREATE OR REPLACE FUNCTION ${qualifiedName}()\nRETURNS void\nLANGUAGE plpgsql\nAS $$\nBEGIN\n  -- implementation\nEND;\n$$;`
        : `CREATE OR REPLACE PROCEDURE ${qualifiedName}()\nLANGUAGE plpgsql\nAS $$\nBEGIN\n  -- implementation\nEND;\n$$;`;
    }
    if (engineId === 'mysql') {
      return isFunction
        ? `DELIMITER $$\nCREATE FUNCTION ${qualifiedName}()\nRETURNS INT\nDETERMINISTIC\nBEGIN\n  RETURN 0;\nEND$$\nDELIMITER ;`
        : `DELIMITER $$\nCREATE PROCEDURE ${qualifiedName}()\nBEGIN\n  -- implementation\nEND$$\nDELIMITER ;`;
    }
    if (engineId === 'sqlserver') {
      return isFunction
        ? `CREATE OR ALTER FUNCTION ${qualifiedName}()\nRETURNS INT\nAS\nBEGIN\n  RETURN 0;\nEND;`
        : `CREATE OR ALTER PROCEDURE ${qualifiedName}\nAS\nBEGIN\n  SET NOCOUNT ON;\n  -- implementation\nEND;`;
    }
    if (engineId === 'oracle') {
      return isFunction
        ? `CREATE OR REPLACE FUNCTION ${qualifiedName}\nRETURN NUMBER\nAS\nBEGIN\n  RETURN 0;\nEND;\n/`
        : `CREATE OR REPLACE PROCEDURE ${qualifiedName}\nAS\nBEGIN\n  NULL;\nEND;\n/`;
    }
  }

  if (objectType === 'package' && engineId === 'oracle') {
    return `CREATE OR REPLACE PACKAGE ${qualifiedName} AS\n  PROCEDURE example;\nEND;\n/\n\nCREATE OR REPLACE PACKAGE BODY ${qualifiedName} AS\n  PROCEDURE example AS\n  BEGIN\n    NULL;\n  END example;\nEND;\n/`;
  }

  if (objectType === 'trigger') {
    if (engineId === 'sqlite') {
      return `CREATE TRIGGER ${qualifiedName}\nAFTER INSERT ON ${tablePlaceholder}\nBEGIN\n  -- SQL statement;\n  SELECT 1;\nEND;`;
    }
    if (engineId === 'postgresql') {
      const triggerName = options.identifierName || qualifiedName;
      return `-- PostgreSQL requires an existing trigger function.\nCREATE TRIGGER ${triggerName}\nBEFORE INSERT ON ${tablePlaceholder}\nFOR EACH ROW\nEXECUTE FUNCTION ${q('trigger_function')}();`;
    }
    if (engineId === 'mysql') {
      return `DELIMITER $$\nCREATE TRIGGER ${qualifiedName}\nBEFORE INSERT ON ${tablePlaceholder}\nFOR EACH ROW\nBEGIN\n  -- implementation\nEND$$\nDELIMITER ;`;
    }
    if (engineId === 'sqlserver') {
      return `CREATE OR ALTER TRIGGER ${qualifiedName}\nON ${tablePlaceholder}\nAFTER INSERT\nAS\nBEGIN\n  SET NOCOUNT ON;\n  -- implementation\nEND;`;
    }
    if (engineId === 'oracle') {
      return `CREATE OR REPLACE TRIGGER ${qualifiedName}\nBEFORE INSERT ON ${tablePlaceholder}\nFOR EACH ROW\nBEGIN\n  NULL;\nEND;\n/`;
    }
  }

  if (objectType === 'type') {
    if (engineId === 'postgresql') {
      return `CREATE TYPE ${qualifiedName} AS (\n  ${q('value')} TEXT\n);`;
    }
    if (engineId === 'sqlserver') {
      return `CREATE TYPE ${qualifiedName} AS TABLE (\n  ${q('value')} NVARCHAR(255) NOT NULL\n);`;
    }
    if (engineId === 'oracle') {
      return `CREATE OR REPLACE TYPE ${qualifiedName} AS OBJECT (\n  ${q('value')} VARCHAR2(255)\n);\n/`;
    }
  }

  if (objectType === 'synonym') {
    return `CREATE SYNONYM ${qualifiedName} FOR ${tablePlaceholder};`;
  }

  if (objectType === 'event' && engineId === 'mysql') {
    return `DELIMITER $$\nCREATE EVENT ${qualifiedName}\nON SCHEDULE EVERY 1 DAY\nDO\nBEGIN\n  -- implementation\nEND$$\nDELIMITER ;`;
  }

  throw new Error(`No CREATE template is available for ${engineId}/${objectType}.`);
}

function alterTemplate(engineId, objectType, qualifiedName, options = {}) {
  const identifierName = options.identifierName || qualifiedName;
  const tableQualifiedName = options.tableQualifiedName || '';

  if (objectType === 'table') {
    return `ALTER TABLE ${qualifiedName}\n  -- ADD COLUMN ...;`;
  }
  if (objectType === 'view') {
    if (engineId === 'sqlserver') return `CREATE OR ALTER VIEW ${qualifiedName} AS\n-- SELECT ...;`;
    if (['postgresql', 'oracle'].includes(engineId)) {
      return `CREATE OR REPLACE VIEW ${qualifiedName} AS\n-- SELECT ...;`;
    }
    if (engineId === 'mysql') return `ALTER VIEW ${qualifiedName} AS\n-- SELECT ...;`;
    if (engineId === 'sqlite') {
      return `-- SQLite does not implement ALTER VIEW. Keep the definition, drop the view, and create it again.\n-- DROP VIEW ${qualifiedName};\n-- CREATE VIEW ${qualifiedName} AS SELECT ...;`;
    }
  }
  if (objectType === 'materializedView') {
    if (engineId === 'oracle') {
      return `ALTER MATERIALIZED VIEW ${qualifiedName}\n  -- COMPILE;`;
    }
    return `ALTER MATERIALIZED VIEW ${qualifiedName}\n  -- RENAME TO new_name;`;
  }
  if (objectType === 'procedure' || objectType === 'function') {
    const keyword = objectType.toUpperCase();
    if (engineId === 'postgresql') return `ALTER ${keyword} ${qualifiedName}()\n  -- ...;`;
    if (engineId === 'sqlserver') return `CREATE OR ALTER ${keyword} ${qualifiedName}\nAS\n-- implementation`;
    if (engineId === 'oracle') return `ALTER ${keyword} ${qualifiedName} COMPILE;`;
    if (engineId === 'mysql') return `ALTER ${keyword} ${qualifiedName}\n  -- COMMENT '...';`;
  }
  if (objectType === 'package' && engineId === 'oracle') {
    return `ALTER PACKAGE ${qualifiedName} COMPILE PACKAGE;\nALTER PACKAGE ${qualifiedName} COMPILE BODY;`;
  }
  if (objectType === 'sequence') {
    return `ALTER SEQUENCE ${qualifiedName}\n  -- INCREMENT BY 1;`;
  }
  if (objectType === 'event' && engineId === 'mysql') return `ALTER EVENT ${qualifiedName}\n  -- ...;`;
  if (objectType === 'type') {
    if (engineId === 'postgresql') {
      return `ALTER TYPE ${qualifiedName}\n  -- ADD VALUE 'new_value';`;
    }
    if (engineId === 'oracle') {
      return `ALTER TYPE ${qualifiedName} COMPILE;`;
    }
    if (engineId === 'sqlserver') {
      return `-- SQL Server does not support ALTER TYPE for changing a type definition.\n-- Review dependencies and use DROP TYPE + CREATE TYPE for ${qualifiedName}.`;
    }
  }
  if (objectType === 'index') {
    if (engineId === 'postgresql') {
      return `ALTER INDEX ${qualifiedName}\n  -- RENAME TO new_name;`;
    }
    if (engineId === 'oracle') {
      return `ALTER INDEX ${qualifiedName} REBUILD;`;
    }
    if (engineId === 'sqlserver' && tableQualifiedName) {
      return `ALTER INDEX ${identifierName} ON ${tableQualifiedName}\n  REBUILD;`;
    }
    if (engineId === 'mysql' && tableQualifiedName) {
      return `-- MySQL 8+: change visibility; other changes are made with ALTER TABLE.\nALTER TABLE ${tableQualifiedName}\n  ALTER INDEX ${identifierName} VISIBLE;`;
    }
    return `-- This engine does not provide a safe generic ALTER INDEX for ${qualifiedName}.\n-- Inspect the definition and use the engine-specific operation.`;
  }
  if (objectType === 'trigger') {
    if (engineId === 'postgresql' && tableQualifiedName) {
      return `ALTER TRIGGER ${identifierName} ON ${tableQualifiedName}\n  -- RENAME TO new_name;`;
    }
    if (engineId === 'oracle') {
      return `ALTER TRIGGER ${qualifiedName} COMPILE;\n-- ALTER TRIGGER ${qualifiedName} ENABLE;`;
    }
    if (engineId === 'sqlserver' && tableQualifiedName) {
      return `ALTER TRIGGER ${qualifiedName}\nON ${tableQualifiedName}\nAFTER INSERT\nAS\nBEGIN\n  SET NOCOUNT ON;\n  -- implementation\nEND;`;
    }
    if (['mysql', 'sqlite'].includes(engineId)) {
      return `-- ${engineId === 'mysql' ? 'MySQL' : 'SQLite'} does not allow a trigger body to be altered directly.\n-- Inspect its definition and use DROP TRIGGER + CREATE TRIGGER for ${qualifiedName}.`;
    }
    return `-- Edit the ${qualifiedName} trigger definition using engine-specific syntax.`;
  }
  if (objectType === 'synonym') {
    return `-- Synonyms are normally replaced with DROP + CREATE.\n-- Object: ${qualifiedName}`;
  }
  return `-- ALTER ${OBJECT_LABELS[objectType] || objectType}: ${qualifiedName}`;
}

function dropTemplate(engineId, objectType, qualifiedName, options = {}) {
  const keywords = {
    table: 'TABLE',
    view: 'VIEW',
    materializedView: 'MATERIALIZED VIEW',
    procedure: 'PROCEDURE',
    function: 'FUNCTION',
    package: 'PACKAGE',
    index: 'INDEX',
    trigger: 'TRIGGER',
    sequence: 'SEQUENCE',
    type: 'TYPE',
    synonym: 'SYNONYM',
    event: 'EVENT',
  };
  const keyword = keywords[objectType];
  if (!keyword) throw new Error(`Invalid object type: ${objectType}`);

  if (objectType === 'index' && options.tableQualifiedName) {
    if (engineId === 'mysql' && String(options.objectName || '').toUpperCase() === 'PRIMARY') {
      return `ALTER TABLE ${options.tableQualifiedName} DROP PRIMARY KEY;`;
    }
    if (engineId === 'sqlserver' && options.isConstraint) {
      return `ALTER TABLE ${options.tableQualifiedName} DROP CONSTRAINT ${options.identifierName || qualifiedName};`;
    }
    if (engineId === 'postgresql' && options.constraintName) {
      return `ALTER TABLE ${options.tableQualifiedName} DROP CONSTRAINT IF EXISTS ${options.constraintName};`;
    }
    if (['mysql', 'sqlserver'].includes(engineId)) {
      return `DROP INDEX ${options.identifierName || qualifiedName} ON ${options.tableQualifiedName};`;
    }
  }

  if (
    objectType === 'trigger' &&
    engineId === 'postgresql' &&
    options.tableQualifiedName
  ) {
    return `DROP TRIGGER IF EXISTS ${options.identifierName || qualifiedName} ON ${options.tableQualifiedName};`;
  }

  const supportsIfExists = ['sqlite', 'postgresql', 'mysql'].includes(engineId);
  return `DROP ${keyword}${supportsIfExists ? ' IF EXISTS' : ''} ${qualifiedName};`;
}

module.exports = {
  OBJECT_LABELS,
  OBJECT_TYPES_BY_ENGINE,
  alterTemplate,
  createTemplate,
  dropTemplate,
  objectTypesForEngine,
};
